<h2>Listado de calendarios</h2>

<div class="row">
	<div class="col-md-12">
		<a class="btn btn-success btnAddTareas" href="<?php echo APP_URL."calendarios/add"; ?>">Agregar calendarios</a>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<table class="table table-striped">
			<tr>
				<th>ID</th>
				<th>Nombre</th>
				<th>Acciones</th>
			</tr>
			<?php foreach ($this->calendarios as $calendario): ?>
			<tr>
				<td><?php echo $calendario["id"]; ?></td>
				<td><?php echo $calendario["nombre"]; ?></td>
				<td><?php ?>
					<a href="<?php echo APP_URL."calendarios/edit/".$calendario['id']; ?>">Editar</a>
					<a href="<?php echo APP_URL."calendarios/delete/".$calendario['id']; ?>">Eliminar</a>
				</td>
			</tr>	
			<?php endforeach; ?>
		</table>
	</div>
</div>
