<h2>Listado de usuarios</h2>
<div class="row">
	<div class="col-md-12">
		<a class="btn btn-success btnAddTareas" href="<?php echo APP_URL."usuarios/add"; ?>">Agregar usuarios</a>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<table class="table table-hover">
			<tr>
				<th>ID</th>
				<th>Nombre</th>
				<th>Fecha</th>
				
				<th>Estatus</th>
				<th>Accion</th>
			</tr>
			<?php foreach ($this->usuarios as $usuario): ?>
			<tr>
				<td><?php echo $usuario["id"]; ?></td>
				<td><?php echo $usuario["email"]; ?></td>
				<td><?php echo $usuario["username"]; ?></td>
				
				<td><?php echo $usuario["status"]; ?></td>
				<td><?php ?>
					<a href="<?php echo APP_URL."usuarios/edit/".$usuario["id"]; ?>">Editar</a>
					<a href="<?php echo APP_URL."usuarios/delete/".$usuario["id"]; ?>">Eliminar</a>
				</td>
			</tr>	
			<?php endforeach; ?>
		</table>
	</div>
</div>
