<h2>Listado de categorias</h2>

<div class="row">
	<div class="col-md-12">
		<a class="btn btn-success btnAddTareas" href="<?php echo APP_URL."categorias/add"; ?>">Agregar categorias</a>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<table class="table table-striped">
			<tr>
				<th>ID</th>
				<th>Nombre</th>
				<th>Acciones</th>
			</tr>
			<?php foreach ($this->categorias as $categoria): ?>
			<tr>
				<td><?php echo $categoria["id"]; ?></td>
				<td><?php echo $categoria["nombre"]; ?></td>
				<td><?php ?>
					<a href="<?php echo APP_URL."categorias/edit/".$categoria['id']; ?>">Editar</a>
					<a href="<?php echo APP_URL."categorias/delete/".$categoria['id']; ?>">Eliminar</a>
				</td>
			</tr>	
			<?php endforeach; ?>
		</table>
	</div>
</div>
