<h2>Editar tarea</h2>

<form action="<?php echo APP_URL."eventos/edit"; ?>" method="POST">
		<input type="hidden" name="id" value="<?php echo $this->eventos["id"]; ?>">
		<p>Titulo: <input type="text" name="titulo" value="<?php echo $this->eventos["titulo"]; ?>"></p>
		<p>Categoria:
		    <select name="calendarios_id">
				<?php foreach ($this->calendarios as $calendario): 
				
		        if ($calendario["id"] == $this->calendarios["calendario_id"]): ?>
		        
		        <option value="<?php echo $calendario["id"]; ?>"><?php echo $calendario["nombre"]; ?></option>
		        
		        <?php else: ?>
		        
		        <option value="<?php echo $calendario["id"]; ?>"><?php echo $calendario["nombre"]; ?></option>
		        
		        <?php endif; 
				
				endforeach; ?>
		        
		    </select>
    
    </p>
		<p>Fecha: <input type="text" name="fecha" value="<?php echo $this->eventos["fecha"]; ?>"></p>
		<p>Lugar: <input type="text" name="prioridad" value="<?php echo $this->eventos["lugar"]; ?>"></p>
		<p><input type="submit"></p>
</form>